name: Convert HTML to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install wkhtmltopdf
      run: sudo apt-get install wkhtmltopdf

    - name: Convert HTML to PDF
      run: wkhtmltopdf variables.html variables.pdf

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./cheatsheets/variables/my-cheatsheet.pdf
        git commit -m "Add generated PDF"
        git push
