name: Convert HTML to PDF

on:
  push:
    paths:
      - '.\cheatsheets\Variables and data types\variables.html' # Specify the path to your HTML file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Convert HTML to PDF
        run: |
          wkhtmltopdf .\cheatsheets\Variables and data types\variables.html output.pdf
          # Adjust the input and output paths as needed

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: converted-pdf
          path: output.pdf
